spring:
  datasource:
    username: postgres
    password: fair-reviews
    url: jdbc:postgresql://localhost:5432/fair-reviews
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
